language: generic
os: linux
dist: xenial

jobs:
  include:
    - os: linux
      language: node_js
      node_js: "6.16"
      branches:
         only: master

    - os: windows
      language: node_js
      node_js: "8.11.3"
      branches:
        only: master

    - os: osx
      language: node_js
      node_js: "6.16"
      branches:
        only: master

    - stage: deploy
      os: osx
      language: generic
      before_install: skip
      script: skip

      branches:
        only:
          deploy

      before_deploy:
        - git config --local user.name "srikar45"
        - git config --local user.email "srikarreddygit@gmail.com"
        - cd pkg && make update VERSION=`node -p "require('../package.json').version"`
        - export TRAVIS_TAG=`node -p "require('../package.json').version"`
        - git tag `node -p "require('../package.json').version"`"

      deploy:
        provider: releases
        on:
          branch: releases
        token: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: dist/*

    - stage: test-linux
      os: linux
      language: generic
      before_install: skip

      branches:
        only:
          - deploy
      script: curl -O https://github.com/gitsrikarreddy/server-node-1/releases/download/`node -p "require('./package.json').version"`/hapi-server-`node -p "require('./package.json').version"`-darwin-x64.tgz; tar zxvf hapi-server-`node -p "require('./package.json').version"`-darwin-x64.tgz; cd hapi-server-`node -p "require('./package.json').version"`; ./hapi-server test

before_install:
  - npm i

script:
  - npm test

notifications:
  email:
    recipients:
      - ksreddy9945@gmail.com
  on_success: change
  on_failure: always
